version: "3"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    container_name: oj-judge
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:12358
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=<GENERATE_A_SECURE_TOKEN_HERE>
      # - judger_debug=1

  oj-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-onlinejudge-backend:latest
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
      - ./frontend/dist:/app/dist
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - POSTGRES_HOST=oj-postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=oj-redis
      - REDIS_PORT=6379
      - JUDGE_SERVER_TOKEN=<SAME_TOKEN_AS_ABOVE>
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"

volumes:
  postgres-data: